package rs.pedjaapps.eventlogger.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import rs.pedjaapps.eventlogger.model.Event;
import rs.pedjaapps.eventlogger.model.Icon;

import rs.pedjaapps.eventlogger.model.EventDao;
import rs.pedjaapps.eventlogger.model.IconDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig iconDaoConfig;

    private final EventDao eventDao;
    private final IconDao iconDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        iconDaoConfig = daoConfigMap.get(IconDao.class).clone();
        iconDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        iconDao = new IconDao(iconDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(Icon.class, iconDao);
    }
    
    public void clear() {
        eventDaoConfig.getIdentityScope().clear();
        iconDaoConfig.getIdentityScope().clear();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public IconDao getIconDao() {
        return iconDao;
    }

}
