package rs.pedjaapps.eventlogger.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import rs.pedjaapps.eventlogger.model.Event;
import rs.pedjaapps.eventlogger.model.Icon;

import rs.pedjaapps.eventlogger.model.EventDao;
import rs.pedjaapps.eventlogger.model.IconDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDaoConfig;
    private final DaoConfig iconDaoConfig;

    private final EventDao eventDao;
    private final IconDao iconDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDaoConfig = daoConfigMap.get(EventDao.class).clone();
        eventDaoConfig.initIdentityScope(type);

        iconDaoConfig = daoConfigMap.get(IconDao.class).clone();
        iconDaoConfig.initIdentityScope(type);

        eventDao = new EventDao(eventDaoConfig, this);
        iconDao = new IconDao(iconDaoConfig, this);

        registerDao(Event.class, eventDao);
        registerDao(Icon.class, iconDao);
    }
    
    public void clear() {
        eventDaoConfig.clearIdentityScope();
        iconDaoConfig.clearIdentityScope();
    }

    public EventDao getEventDao() {
        return eventDao;
    }

    public IconDao getIconDao() {
        return iconDao;
    }

}
