package rs.pedjaapps.eventlogger.model;

import android.os.Parcel;
import android.os.Parcelable;

import org.greenrobot.greendao.DaoException;
import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.ToOne;

import java.util.Date;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS
// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "EVENT".
 */
@Entity(active = true)
public class Event implements Parcelable {

    @Id
    private Long id;

    @NotNull
    private java.util.Date timestamp;
    private String short_desc;
    private String long_desc;
    private int type;
    private int level;
    private Long icon_id;

    /** Used to resolve relations */
    @Generated(hash = 2040040024)
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    @Generated(hash = 1542254534)
    private transient EventDao myDao;

    @ToOne(joinProperty = "icon_id")
    private Icon icon;

    @Generated(hash = 1941781955)
    private transient Long icon__resolvedKey;

    @Generated(hash = 344677835)
    public Event() {
    }

    public Event(Long id) {
        this.id = id;
    }

    @Generated(hash = 1709928360)
    public Event(Long id, @NotNull java.util.Date timestamp, String short_desc, String long_desc, int type, int level, Long icon_id) {
        this.id = id;
        this.timestamp = timestamp;
        this.short_desc = short_desc;
        this.long_desc = long_desc;
        this.type = type;
        this.level = level;
        this.icon_id = icon_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public java.util.Date getTimestamp() {
        return timestamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimestamp(@NotNull java.util.Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getShort_desc() {
        return short_desc;
    }

    public void setShort_desc(String short_desc) {
        this.short_desc = short_desc;
    }

    public String getLong_desc() {
        return long_desc;
    }

    public void setLong_desc(String long_desc) {
        this.long_desc = long_desc;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public Long getIcon_id() {
        return icon_id;
    }

    public void setIcon_id(Long icon_id) {
        this.icon_id = icon_id;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(hash = 2034234485)
    public Icon getIcon() {
        Long __key = this.icon_id;
        if (icon__resolvedKey == null || !icon__resolvedKey.equals(__key)) {
            final DaoSession daoSession = this.daoSession;
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            IconDao targetDao = daoSession.getIconDao();
            Icon iconNew = targetDao.load(__key);
            synchronized (this) {
                icon = iconNew;
                icon__resolvedKey = __key;
            }
        }
        return icon;
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated(hash = 1539831925)
    public void setIcon(Icon icon) {
        synchronized (this) {
            this.icon = icon;
            icon_id = icon == null ? null : icon.getId();
            icon__resolvedKey = icon_id;
        }
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#delete(Object)}.
     * Entity must attached to an entity context.
     */
    @Generated(hash = 128553479)
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.delete(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#update(Object)}.
     * Entity must attached to an entity context.
     */
    @Generated(hash = 713229351)
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.update(this);
    }

    /**
     * Convenient call for {@link org.greenrobot.greendao.AbstractDao#refresh(Object)}.
     * Entity must attached to an entity context.
     */
    @Generated(hash = 1942392019)
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }
        myDao.refresh(this);
    }

    @Override
    public int describeContents()
    {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags)
    {
        dest.writeValue(this.id);
        dest.writeLong(timestamp != null ? timestamp.getTime() : -1);
        dest.writeString(this.short_desc);
        dest.writeString(this.long_desc);
        dest.writeInt(this.type);
        dest.writeInt(this.level);
        if(icon_id != null)dest.writeLong(this.icon_id);
    }

    private Event(Parcel in)
    {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        long tmpTimestamp = in.readLong();
        this.timestamp = tmpTimestamp == -1 ? null : new Date(tmpTimestamp);
        this.short_desc = in.readString();
        this.long_desc = in.readString();
        this.type = in.readInt();
        this.level = in.readInt();
        this.icon_id = in.readLong();
    }

    public static Creator<Event> CREATOR = new Creator<Event>()
    {
        public Event createFromParcel(Parcel source)
        {
            return new Event(source);
        }

        public Event[] newArray(int size)
        {
            return new Event[size];
        }
    };

    @Override
    public String toString()
    {
        return "Event{" +
                "id=" + id +
                ", timestamp=" + timestamp +
                ", short_desc='" + short_desc + '\'' +
                ", long_desc='" + long_desc + '\'' +
                ", type=" + type +
                ", level=" + level +
                '}';
    }

    /** called by internal mechanisms, do not call yourself. */
    @Generated(hash = 1459865304)
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEventDao() : null;
    }

}
